# Generated by Django 3.0 on 2021-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.CharField(default=None, max_length=15)),
                ('publishedAt', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
